name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push packages to ghcr.io

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # If your project uses submodules (like the reference web-sugar-startup did),
      # you might need to add:
      # with:
      #   submodules: 'recursive'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # Using Eclipse Temurin, consistent with Dockerfile

    - name: Cache SBT dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/*.scala', 'project/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run SBT stage
      run: sbt clean stage # This command compiles the app and stages it in target/universal/stage

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # The Dockerfile is in the root
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
